### PR TITLE
Https agent added to options

### PR DESCRIPTION
**Pull request by txirinedu**
Added agent from options to https call (https://nodejs.org/api/https.html#https_https_request_options_callback) in order to be able to send push notifications from a network behind a proxy.

### CODE REVIEW

**Comment by gauntface** [comment]
cc @marco-c 

Couple of requests:
- Can you add some tests to ensure this isn't lost in the future.
- Can you update the readme with info on the option

Lastly I'm not aware of this option and what is does. Can you write up an example of the input and why that would help for a network behind a proxy?

Cheers,
Matt

**Comment by marco-c** [comment]
@txirinedu ping?

**Comment by txirinedu** [comment]
Hi Marco,

It's been a very busy time for me these days, I'll try to respond to your questions during the next weekend.

Sorry about that,

**Comment by prodrigestivill** [comment]
If I understand this correctly, this will also add the possibility to support keep-alive pool of sockets on upstream. And sending multiple notifications per TCP connection. This sounds awesome!

By configuring the agent in the server code before passing the options to the library.
```javascript
var options = {/*...*/};
options.agent = new http.Agent({
  keepAlive: true,
  maxSockets: 1,
  keepAliveMsecs: 3000
});
wp.sendNotification(/*sub*/,/*payload*/,options);
```
Example of using keep alive in node extracted from [stackoverflow](http://stackoverflow.com/questions/28229044/http-keep-alive-in-node-js#answer-33514724).

**Comment by edweena** [comment]
any status update on this?

**Comment by raviten** [comment]
+1

**Comment by raviten** [comment]
@marco-c 
Any expected merge date?

**Comment by marco-c** [comment]
>  Any expected merge date?

We are waiting on @txirinedu.

**Comment by marco-c** [comment]
I'm going to close this given lack of response from the author.

**Pull request closed without merging**
