### PR TITLE
Bring the tests back to life

### PR DESCRIPTION
**Pull request by gauntface**
This should add Firefox 49 + tests back on Travis.

### CODE REVIEW

**Comment by gauntface** [comment]
This was working locally. Got plenty of problems on travis so will have to take a look and see what I can do.

**Comment by gauntface** [comment]
@marco-c could you take a look at #205 and this PR when you get chance.

**Comment by gauntface** [comment]
Closes #201 and #179

**Comment by marco-c** [comment]
The tests with Firefox are failing on Mac, maybe because of the rate limit issue?

Let's merge this first and then investigate the other failure in a follow-up.

**Pull request merged**
