### PR TITLE
Require https-proxy-agent only when actually needed

### PR DESCRIPTION
**Pull request by xPaw**
`https-proxy-agent` patches core Node methods in `https` for whatever reason, and that breaks unrelated code. In our app we don't use proxy, and the mere fact that `web-push` requires the proxy package, it breaks other code.

See https://github.com/TooTallNate/node-agent-base/issues/35 and https://github.com/sindresorhus/got/issues/951

### CODE REVIEW

**Comment by marco-c** [comment]
It'd be nice to have a test for the proxy option (currently we don't have any), to ensure it doesn't break.

**Comment by xPaw** [comment]
I don't have the motivation to look into how to achieve that, sorry.

I'm not sure `https-proxy-agent` is a good package to begin with, when it override core node methods.

**Comment by xPaw** [comment]
Thanks. Will you be able to push a new release out with this?

**Comment by marco-c** [comment]
> Thanks. Will you be able to push a new release out with this?

Yes, I'll do it shortly.

**Comment by marco-c** [comment]
Ah, you'll need to add `// eslint-disable-line global-require` to avoid the eslint error.

**Comment by marco-c** [comment]
I've released v3.4.2.

**Pull request merged**
