### PR TITLE
fcm/send/ endpoint supports AES_128_GCM

### PR DESCRIPTION
**Pull request by pinarx**
Remove the FCM endpoint modification for AES_128_GCM content encoding

### CODE REVIEW

**Comment by marco-c** [comment]
@pinarx do you have a reference that shows that this is now supported on the "normal" URL?

**Comment by pinarx** [comment]
You can confirm it using this demo and by simply replacing the endpoint to point to /fcm/send rather than /wp/.

**Comment by MartijnDwars** [comment]
Does this mean Google made a change such that this replacement is no longer necessary? The Selenium tests only check with newly created subscriptions; what if we have an old endpoint that still contains `/fcm/send`?

**Comment by pinarx** [comment]
The replacement is no longer necessary and the /fcm/send endpoint now supports the new VAPID format. Old tokens should continue to work.

**Pull request merged**
