### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**
See https://www.chromestatus.com/features/5748876422152192

### CODE REVIEW

**Comment by gauntface** [comment]
Couple of comments and cc @marco-c for your thoughts.

1.) Should we move browser support into a table and have sections for feature support and notes at the bottom for things like (Opera only works on Mobile).

2.) Samsung browser should be added to that list

**Comment by marco-c** [comment]
I agree with @gauntface.

Something like this:

| Browser | Desktop | Mobile | VAPID | Notes |
| ------------- | ------------ | ----------- | ---------- | --------- |
| a browser    | X           | X | X | |
| a browser where VAPID isn't supported  | X           |   X |  | VAPID support is being worked on, LINK_TO_THE_ISSUE_TRACKER

I would remove the version number, unless a feature is supported in a non-stable version of a browser.

**Comment by marco-c** [comment]
Hey @FluorescentHallucinogen, were you planning on updating this PR?

**Comment by FluorescentHallucinogen** [comment]
@marco-c
No, I've delete­d my fork and don't know how to update this pull request. (Is it possible at all?)
Feel free to update README.md yourself.

**Comment by marco-c** [comment]
>  No, I've delete­d my fork and don't know how to update this pull request. (Is it possible at all?)

You can create a new one if you want :)

**Pull request closed without merging**
