### PR TITLE
VAPID Expiration within 12 Hours

### PR DESCRIPTION
**Pull request by gauntface**
May be a solution to #254

### CODE REVIEW

**Comment by marco-c** [comment]
Why does setting the expiration to 12 hours instead of 24 hours help?

Need to fix some linting errors.

**Comment by gauntface** [comment]
The spec defines that 24 hours is the max expiration for a certificate. My understanding is that FCM is ensuring this isn't exceeded and failing if it does.

By defining the default expiration as 24 hours in the future, there is no margin for error with the machines local time. The result is that if the local time is out by a couple of minutes, you may exceed the 24 hour limit resulting in an invalid VAPID header.

By using 12 hours as the default, we are just introducing a margin of error if the local time is set in the future.

**Comment by marco-c** [comment]
> The spec defines that 24 hours is the max expiration for a certificate. My understanding is that FCM is ensuring this isn't exceeded and failing if it does.

Ah, I see, I thought the failure was due to the expiration being in the past (for users who had a clock set to the past).

**Comment by marco-c** [comment]
Once Travis is happy, I'm going to merge this and release a point release.

**Comment by gauntface** [comment]
The clock error can be caused by both future and past. This change will change from 24hr margin of error for past and 0 margin of error for future to 12hr for both.

@p-nowak did comment that this solved the problem for one of his test cases, so I think it's a useful change. Obviously better error messages would help greatly with this.

**Comment by marco-c** [comment]
I've released `3.2.1`.

**Pull request merged**
